package boundary;

import java.io.IOException;

import control.Server;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.control.TextField;
import javafx.scene.paint.Color;
import javafx.stage.Modality;
import javafx.stage.Stage;
/**
 * This class is responsible for opening the server connection, and connection to DB.
 */
public class ServerConfigurationController {
	
    @FXML
    private TextField hostTF;

    @FXML
    private TextField portTF;

    @FXML
    private TextField dbTF;

    @FXML
    private TextField usernameTF;

    @FXML
    private Label successMessage;
    
    @FXML
    private TextField passwordTF;

    @FXML
    private Button connectButton;
    
    @FXML
    private Button externalButton;

    /**
     * Called when the server operator clicks on "connect" button, it opens a server connection so it's ready to listen for clients,
     * then connects to the DB. If any problem is encountered an error message is displayed, otherwise a success message is displayed.
     * @param event - auto-generated by SceneBuilder.
     */
    @FXML
    void connectToDBHandler(ActionEvent event) {
    	if(Server.openServerConnection(usernameTF.getText(), passwordTF.getText(), hostTF.getText(),dbTF.getText())==true)
    	{
    		successMessage.setText("connection success");
    		successMessage.setTextFill(Color.GREEN);
    		externalButton.setVisible(true);
    	}
    	else {
    		successMessage.setText("connection failed");
    		successMessage.setTextFill(Color.RED);
    	}
    	
    }
    
    
    @FXML
    void ExternalSystemHandler(ActionEvent event) throws IOException {
    	Stage primaryStage = new Stage();
		primaryStage.setAlwaysOnTop(true);
		primaryStage.initModality(Modality.APPLICATION_MODAL);
		FXMLLoader loader = new FXMLLoader();
		Parent root = loader.load(getClass().getResource("/boundary/ExternalSystemGUI.fxml").openStream());
		primaryStage.setScene(new Scene(root));
		primaryStage.setTitle("System");
		primaryStage.show();
    }
    
}
